# Generated by Django 4.1.2 on 2022-10-13 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lukenyaBackendApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='offer',
        ),
    ]
