# Generated by Django 4.1.2 on 2022-10-13 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lukenyaBackendApp', '0002_remove_rooms_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=100)),
                ('cat_desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_header', models.CharField(max_length=100)),
                ('news_description', models.TextField()),
                ('news_img', models.ImageField(upload_to='lukenyaGetawayNews')),
                ('news_date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='customer_designation',
            field=models.TextField(default='Customer'),
        ),
    ]
