# Generated by Django 4.1.2 on 2022-10-13 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lukenyaBackendApp', '0003_category_news_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=100)),
                ('image_desc', models.TextField()),
                ('image_url', models.ImageField(upload_to='lukenyaGallery')),
            ],
        ),
        migrations.CreateModel(
            name='image_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('category_desc', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='customer_designation',
            field=models.CharField(default='Customer', max_length=200),
        ),
    ]
