# Generated by Django 4.1.2 on 2022-10-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lukenyaBackendApp', '0004_gallery_image_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rooms',
            old_name='price',
            new_name='kes_price',
        ),
        migrations.AddField(
            model_name='rooms',
            name='usd_price',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
    ]
