# Generated by Django 4.1.2 on 2022-10-16 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lukenyaBackendApp', '0005_rename_price_rooms_kes_price_rooms_usd_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'gallery', 'verbose_name_plural': 'galleries'},
        ),
        migrations.AlterModelOptions(
            name='image_category',
            options={'verbose_name': 'image category', 'verbose_name_plural': 'image categories'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'news', 'verbose_name_plural': 'news'},
        ),
        migrations.AlterModelOptions(
            name='rooms',
            options={'verbose_name': 'room', 'verbose_name_plural': 'rooms'},
        ),
        migrations.AlterModelOptions(
            name='testimonials',
            options={'verbose_name': 'testimonial', 'verbose_name_plural': 'testimonials'},
        ),
        migrations.AddField(
            model_name='gallery',
            name='altText',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='image_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lukenyaBackendApp.image_category'),
        ),
        migrations.AddField(
            model_name='image_category',
            name='uniqueId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
